/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./components/**/*.{js,vue,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./app.vue",
    "./error.vue",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#864d61",
        "error-container": "#ffdad6",
        "background": "#fbf9f8",
        "on-error-container": "#93000a",
        "inverse-surface": "#303030",
        "surface-container-high": "#eae8e7",
        "inverse-on-surface": "#f2f0f0",
        "outline": "#837377",
        "surface-container": "#efeded",
        "on-error": "#ffffff",
        "secondary-fixed": "#b2f2bb",
        "on-tertiary": "#ffffff",
        "surface-bright": "#fbf9f8",
        "on-primary-fixed": "#360b1e",
        "error": "#ba1a1a",
        "on-background": "#1b1c1c",
        "on-tertiary-fixed-variant": "#4e4721",
        "tertiary-container": "#d6cb9a",
        "surface-dim": "#dbd9d9",
        "on-secondary-fixed": "#00210b",
        "on-surface-variant": "#514347",
        "on-secondary-container": "#357044",
        "tertiary-fixed": "#efe3b0",
        "primary-fixed-dim": "#fab3ca",
        "tertiary-fixed-dim": "#d2c796",
        "primary-container": "#ffb7ce",
        "secondary": "#2f6a3f",
        "on-secondary": "#ffffff",
        "outline-variant": "#d5c2c6",
        "surface-container-highest": "#e4e2e2",
        "primary-fixed": "#ffd9e3",
        "on-primary-container": "#7b4458",
        "on-surface": "#1b1c1c",
        "tertiary": "#665f36",
        "on-tertiary-fixed": "#211c00",
        "surface-container-low": "#f5f3f3",
        "on-secondary-fixed-variant": "#145129",
        "surface": "#fbf9f8",
        "secondary-fixed-dim": "#96d5a0",
        "secondary-container": "#b2f2bb",
        "surface-variant": "#e4e2e2",
        "on-primary": "#ffffff",
        "inverse-primary": "#fab3ca",
        "on-tertiary-container": "#5d552e",
        "on-primary-fixed-variant": "#6a364a",
        "primary": "#ec4899"
      },
      fontFamily: {
        'plus-jakarta': ['"Plus Jakarta Sans"', 'sans-serif'],
        'vietnam': ['"Be Vietnam Pro"', 'sans-serif'],
      },
    },
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        kawaii: {
          "primary": "#ec4899",
          "secondary": "#2f6a3f",
          "accent": "#665f36",
          "neutral": "#303030",
          "base-100": "#fbf9f8",
          "info": "#ffb7ce",
          "success": "#b2f2bb",
          "warning": "#d6cb9a",
          "error": "#ba1a1a",
        },
      },
    ],
  },
}
